# Generated by Django 4.0.2 on 2022-03-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('child_name', models.CharField(max_length=50)),
                ('child_age', models.IntegerField()),
                ('child_gender', models.CharField(max_length=50)),
                ('recent_vaccinations', models.CharField(max_length=50)),
            ],
        ),
    ]
