# Generated by Django 4.0.2 on 2022-03-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.hospital')),
            ],
        ),
    ]
