# Generated by Django 4.0.2 on 2022-03-15 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_vaccine_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('vaccinated', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniapp.vaccine_schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='miniapp.user')),
                ('vaccine_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miniapp.vaccine')),
            ],
        ),
    ]
